# Generated by Django 3.2.13 on 2022-07-06 16:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announce',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('regdate', models.DateTimeField(default=datetime.datetime.now)),
                ('views', models.IntegerField(default=0)),
                ('contents', models.TextField()),
            ],
            options={
                'db_table': 'announce',
                'ordering': ['-id'],
            },
        ),
    ]
