# Generated by Django 3.2.13 on 2022-07-07 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teamplayer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('regdate', models.DateTimeField()),
                ('views', models.IntegerField(default=0)),
                ('contents', models.TextField()),
            ],
            options={
                'db_table': 'teamplayer',
                'ordering': ['-id'],
            },
        ),
    ]
