# Generated by Django 4.0.6 on 2022-07-10 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_teamplayer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announce',
            old_name='contents',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='announce',
            old_name='views',
            new_name='view',
        ),
    ]
