# Generated by Django 3.2.13 on 2022-07-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_rename_contents_announce_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('regdate', models.CharField(max_length=20)),
                ('view', models.IntegerField(default=0)),
                ('content', models.TextField()),
                ('category', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'news',
                'ordering': ['-id'],
            },
        ),
        migrations.RenameField(
            model_name='teamplayer',
            old_name='contents',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='teamplayer',
            old_name='views',
            new_name='view',
        ),
        migrations.AlterField(
            model_name='announce',
            name='regdate',
            field=models.DateTimeField(),
        ),
    ]
