# Generated by Django 3.2.13 on 2022-07-11 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_auto_20220711_1453'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Announce',
        ),
        migrations.DeleteModel(
            name='Teamplayer',
        ),
    ]
